export const APPLICATION_CREATE_REQUEST = "APPLICATION_CREATE_REQUEST";
export const APPLICATION_CREATE_SUCCESS = "APPLICATION_CREATE_SUCCESS";
export const APPLICATION_CREATE_FAILS = "APPLICATION_CREATE_FAILS";
export const ALL_USER_APPLICATIONS_REQUEST = "ALL_USER_APPLICATIONS_REQUEST"
export const ALL_USER_APPLICATIONS_SUCCESS = "ALL_USER_APPLICATIONS_SUCCESS"
export const ALL_USER_APPLICATIONS_FAILS = "ALL_USER_APPLICATIONS_FAILS"